name: Crear rama release

# Controls when the action will run. 
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

# Workflow pruebas
jobs:
  crearRamaRelease:
    name: crear rama Release
    runs-on: windows-latest
    if: ${{ contains(github.event.head_commit.message, 'Release') }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Crear rama 
        run: | 
          git checkout -b release
          git push -f -u origin release
  
  mergeReleaseMain:
    name: merge Release Main
    needs: crearRamaRelease
    runs-on: windows-latest
    steps:
      - name: release -> main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
          commit-message: "Se mezcló la rama release con main"
