name: Merge de la rama feature con develop

# Controls when the action will run. 
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

# Workflow pruebas
jobs:
  job1:
    name: PruebasE2E
    runs-on: windows-latest
    if: ${{ contains(github.event.head_commit.message, 'Release') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Run Espresso Tests
      uses: reactivecircus/android-emulator-runner@v1
      with: 
          api-level: 28
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest -Pcucumber -Ptags="@e2e"

  crearRamaRelease:
    name: crear rama Release
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Crear rama 
        run: | 
          git checkout -b release
          git push -f -u origin release
  
  mergeReleaseMain:
    name: merge Release Main
    needs: crearRamaRelease
    runs-on: windows-latest
    steps:
      - name: release -> main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
          commit-message: "Se mezcló la rama release con main"
